import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'emulator_config.dart';

/// Placeholder [FirebaseOptions] for the emulators.
///
/// Nothing here is a real Firebase credential: the project only exists in the
/// emulators (`demo-` prefix). Replace the whole file with the one generated by
/// `flutterfire configure` to target a real project.
class DefaultFirebaseOptions {
  /// Options for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const _messagingSenderId = '000000000000';

  /// Web placeholder.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: emulatorApiKey,
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: _messagingSenderId,
    projectId: emulatorProjectId,
    authDomain: '$emulatorProjectId.firebaseapp.com',
  );

  /// Android placeholder.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: emulatorApiKey,
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: _messagingSenderId,
    projectId: emulatorProjectId,
  );

  /// iOS placeholder.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: emulatorApiKey,
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: _messagingSenderId,
    projectId: emulatorProjectId,
    iosBundleId: 'com.tekartik.uiAuthEmulatorExample',
  );

  /// macOS placeholder.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: emulatorApiKey,
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: _messagingSenderId,
    projectId: emulatorProjectId,
    iosBundleId: 'com.tekartik.uiAuthEmulatorExample',
  );
}
