name: tekartik_firebase_flutter_ui_auth
description: "Firebase Flutter UI auth"
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  tekartik_app_rx:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_rx
  tekartik_app_rx_utils:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_rx_utils
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      ref: dart3a
      path: auth
  tekartik_firebase_auth_sembast:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      ref: dart3a
      path: auth_sembast
  tekartik_app_rx_bloc:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_rx_bloc
  tekartik_app_flutter_bloc:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_bloc
  tekartik_app_flutter_widget:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_widget
  firebase_ui_auth: '>=1.15.0'
  tekartik_firebase_ui_auth:
    git:
      url: https://github.com/tekartik/firebase_ui.dart
      ref: dart3a
      path: packages/firebase_ui_auth
  tekartik_firebase_auth_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      ref: dart3a
      path: auth_flutter
  tekartik_firebase_flutter:
    git:
      url: https://github.com/tekartik/firebase_flutter
      ref: dart3a
      path: firebase_flutter
  firebase_ui_oauth_google: ^1.4.0
  tekartik_app_rx_bloc_flutter:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart3a
      path: app_rx_bloc

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0"
  tekartik_lints_flutter:
    git:
      url: https://github.com/tekartik/common_flutter.dart
      ref: dart3a
      path: packages/lints_flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
resolution: workspace

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
